version: '3.8'

services:

  postgresql-service:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: miguel
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net-sonarqube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  sonarqube-service:
    image: sonarqube:community
    container_name: sonarqube-container
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql-service:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: miguel
      SONARQUBE_JDBC_PASSWORD: 12345
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - net-sonarqube
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 50s
    depends_on:
      postgresql-service:
        condition: service_healthy
    restart: always

volumes:
  postgres-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:

networks:
  net-sonarqube:
    driver: bridge
